### ISSUE TITLE
Can't Enter Map

### ISSUE THREAD

**Issue by Lionhitch** [Vadix88/MonkeMapLoader#20]
I use computer interface to select the map go to details press enter to load it. An orb pops up and I walk into the portal and nothing happens. I click everywhere still nothing.

**Comment by CyorgGit** [comment]
same

**Comment by vrandgaming** [comment]
> I use computer interface to select the map go to details press enter to load it. An orb pops up and I walk into the portal and nothing happens. I click everywhere still nothing.

ok so idk how to fix that but i watch a vid so u just need to install the version that worked 2 month ago

**Comment by In4init3** [comment]
this should be fixed in the current update!
