### ISSUE TITLE
Add Events.OnMapLeave

### ISSUE THREAD

**Issue by Frogrilla** [Vadix88/MonkeMapLoader#35]
The event would help a lot for certain mods such as my MonkeTunes mod - as it allows for the computer to be moved into the map, but it is difficult to make it return to the last position when you leave because there is no event for it.

**Comment by Frogrilla** [comment]
Vadix explained how to do this with OnMapEnter

**Comment by Graicc** [comment]
For anyone else, OnMapEnter callbacks take a bool that represents join / leave
